// Code generated by genlib2. DO NOT EDIT.

package storage

import "unsafe"

func

/* bool */(h *Header[T]) ObjectSlice() []T {
	return h.Raw
}
func (h *Header[T]) Set(i int, x T) {
	h.Raw[i] = x
}
func (h *Header[T]) Get(i int) T {
	return h.Raw[i]
}

/* int */

/* int8 */

/* int16 */

/* int32 */

/* int64 */

/* uint */

/* uint8 */

/* uint16 */

/* uint32 */

/* uint64 */

/* uintptr */

/* float32 */

/* float64 */

/* complex64 */

/* complex128 */

/* string */

/* unsafe.Pointer */
